### PR TITLE
add www.sibalogtv.com to falsepositive.list

### PR DESCRIPTION
**Pull request by g0d33p3rsec**
## Phishing Domain/URL/IP(s):

```
www.sibalogtv.com
```

## Impersonated domain

```

```

## Describe the issue

Adding `www.sibalogtv.com` to the list of false positives to address https://github.com/Phishing-Database/Phishing.Database/issues/972

### Screenshot

<details><summary>Click to expand</summary>

</details>

### CODE REVIEW

**Comment by g0d33p3rsec** [comment]
Review requested as this is my first time adding a site as a false-positive and I want to ensure I added it to the right list.

**Comment by Fernandof28** [comment]
thanks!!

**Comment by spirillen** [comment]
> Review requested as this is my first time adding a site as a false-positive and I want to ensure I added it to the right list.

Could you d me the favor, and tell me which part of https://github.com/Phishing-Database/phishing?tab=readme-ov-file#false-positives that need to be rewritten, to make it easier to understand.

**Comment by g0d33p3rsec** [comment]
> Could you d me the favor, and tell me which part of https://github.com/Phishing-Database/phishing?tab=readme-ov-file#false-positives that need to be rewritten, to make it easier to understand.

The missing section to override my autistic preprocessing 😄

**Comment by spirillen** [comment]
Cool, let's build a showman

**Comment by Fernandof28** [comment]
Hi, the domain still is inside the blacklist in Virus Total,  help me please

**Comment by g0d33p3rsec** [comment]
> Hi, the domain still is inside the blacklist in Virus Total, help me please

I think I see the problem, I added the www subdomain.  One sec, I'll push a fix.
image
image
image

**Comment by Fernandof28** [comment]
thanks!!

**Comment by g0d33p3rsec** [comment]
No worries, I'm just waiting for the secondary rate limit to reset.  Apparently, MSFT is competing w/ GOOG to see which can subject users to the worst UX.

**Comment by g0d33p3rsec** [comment]
@Fernandof28 I have the pull request ready to go, unfortunately it will be a few minutes until GitHub lets me out of API jail.  
image

**Pull request merged**
